### ISSUE TITLE
 Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by 63degrees** [fastly/epoch#223]
angular.js:13550 TypeError: Cannot read property 'x' of undefined
    at a.Epoch.Time.Plot.a._updateTicks (http://localhost:45454/Scripts/epoch.min.js:74:220)
    at a.Epoch.Time.Plot.a._shift (http://localhost:45454/Scripts/epoch.min.js:72:149)
    at a.Epoch.Time.Plot.a._startTransition (http://localhost:45454/Scripts/epoch.min.js:69:457)
    at a.Epoch.Time.Plot.a.push (http://localhost:45454/Scripts/epoch.min.js:71:503)
    at http://localhost:45454/Scripts/ng-epoch.js:80:31
    at n.$digest (http://localhost:45454/Scripts/angular.min.js:142:306)
    at n.$apply (http://localhost:45454/Scripts/angular.min.js:145:249)
    at i.<anonymous> (http://localhost:45454/app/services.js:19:32)
    at i.f.(anonymous function).(anonymous function) (http://localhost:45454/Scripts/jquery.signalR-2.2.0.min.js:8:33219)
    at i.n.event.dispatch (http://localhost:45454/Scripts/jquery-2.2.3.min.js:3:7537)

**Comment by 63degrees** [comment]
This was trying to render an area chart.  dataitem.value = 38.

chartEntry.push({ time: timestamp, y: dataItem.value });

$scope.areaAxes = ['left', 'right', 'bottom'];

**Comment by rsandor** [comment]
Can you show me how you define chartEntry?

**Comment by 63degrees** [comment]
var timestamp = ((new Date()).getTime() / 1000) | 0;
            var chartEntry = [];
            chartEntry.push({ time: 0, y: 0 });
